# SPDX-FileCopyrightText: Copyright (C) 2025-2026 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: java-dependency-security
'on':
  push:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  java-dependency-security:
    uses: fabriciofx/github-workflows/.github/workflows/trivy-security-template.yml@main
