# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: bash-format-test
'on':
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  bash-format-test:
    uses: fabriciofx/github-workflows/.github/workflows/bash-format-template.yml@main
    with:
      working-directory: "bash/test"
