# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: java-codecov-test
'on':
  push:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  java-codecov-test:
    uses: fabriciofx/github-workflows/.github/workflows/java-codecov-template.yml@main
    with:
      working-directory: "java/test"
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
