# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: java-coverage-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  java-coverage-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Configure Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ubuntu-jdk-21-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-jdk-21-maven-
      - name: Checks code coverage
        working-directory: ${{ inputs.working-directory }}
        run: |
          [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
          args=(--errors --batch-mode install)
          profile=$(grep -q "<id>jacoco</id>" pom.xml && echo "-Pjacoco")
          [[ -n "${profile}" ]] && args+=("${profile}")
          ${mvn} "${args[@]}"
