# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: java-sonatype-release-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
    secrets:
      release_keyname:
        description: "GPG key name"
        required: true
      release_passphrase:
        description: "GPG passphrase"
        required: true
      release_username:
        description: "Sonatype username"
        required: true
      release_password:
        description: "Sonatype password"
        required: true
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  actions: read
  security-events: write
  contents: read
jobs:
  java-build-template:
    uses: fabriciofx/github-workflows/.github/workflows/java-build-template.yml@main
  java-sonatype-release-template:
    runs-on: ubuntu-24.04
    needs: java-build-template
    steps:
      - name: Setup Maven settings.xml
        working-directory: ${{ inputs.working-directory }}
        env:
          KEYNAME: ${{ secrets.release_keyname }}
          PASSPHRASE: ${{ secrets.release_passphrase }}
          USERNAME: ${{ secrets.release_username }}
          PASSWORD: ${{ secrets.release_password }}
        run: |
          # Download and install xmlstarlet
          sudo apt-get install -y -qq xmlstarlet

          # Set settings.xml path
          settings="${HOME}/.m2/settings.xml"

          # Add 'central' server
          xmlstarlet ed -L \
            -s "/*[local-name()='settings']/*[local-name()='servers']" \
              -t elem -n "server" -v "" \
            -s "/*[local-name()='settings']/*[local-name()='servers']/server[last()]" \
              -t elem -n "id" -v "oss.sonatype.org" \
            -s "/*[local-name()='settings']/*[local-name()='servers']/server[last()]" \
              -t elem -n "username" -v "${USERNAME}" \
            -s "/*[local-name()='settings']/*[local-name()='servers']/server[last()]" \
              -t elem -n "password" -v "${PASSWORD}" \
            "${settings}"

          # Add 'gpg' profile
          xmlstarlet ed -L \
            -s "/*[local-name()='settings']" -t elem -n "profiles" -v "" \
            -s "/*[local-name()='settings']/*[local-name()='profiles']" \
              -t elem -n "profile" -v "" \
            -s "/*[local-name()='settings']/*[local-name()='profiles']/profile[last()]" \
              -t elem -n "id" -v "gpg" \
            -s "/*[local-name()='settings']/*[local-name()='profiles']/profile[last()]" \
              -t elem -n "properties" -v "" \
            -s "/*[local-name()='settings']/*[local-name()='profiles']/profile[last()]/properties" \
              -t elem -n "gpg.keyname" -v "${KEYNAME}" \
            -s "/*[local-name()='settings']/*[local-name()='profiles']/profile[last()]/properties" \
              -t elem -n "gpg.passphrase" -v "${PASSPHRASE}" \
            "${settings}"
      - name: Release to Sonatype
        working-directory: ${{ inputs.working-directory }}
        run: |
          [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
          ${mvn} --errors --batch-mode deploy -Psonatype -Pgpg -DskipTests=true
