# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: js-duplication-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  js-duplication-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Download Simian
        working-directory: ${{ inputs.working-directory }}
        env:
          TMP: ${{ runner.temp }}
        run: |
          curl -sS -L --retry 3 -o "${TMP}/simian.jar" \
            http://public.yegor256.com/simian.jar
      - name: Check JavaScript code duplication
        working-directory: ${{ inputs.working-directory }}
        env:
          TMP: ${{ runner.temp }}
        run: |
          java -jar "${TMP}/simian.jar" -threshold=16 \
            -ignoreBlocks="simian-off:simian-on" "**/*.js"
