# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: scss-duplication-test
'on':
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  scss-duplication-test:
    uses: fabriciofx/github-workflows/.github/workflows/scss-duplication-template.yml@main
    with:
      working-directory: "format/test"
